# Project settings
project_id = "itsxxdxyigsyqxkeonqr"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://elizabethcarol.netlify.app"
# A list of URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://elizabethcarol.netlify.app/auth/callback", "https://elizabethcarol.netlify.app/auth"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Use custom templates for emails
[auth.email.template.invite]
subject = "You've been invited to Elizabeth Carol's Spiritual Services"
content_path = "supabase/email-templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Email for Elizabeth Carol's Spiritual Services"
content_path = "supabase/email-templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password for Elizabeth Carol's Spiritual Services"
content_path = "supabase/email-templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link for Elizabeth Carol's Spiritual Services"
content_path = "supabase/email-templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirm Your New Email for Elizabeth Carol's Spiritual Services"
content_path = "supabase/email-templates/email-change.html"
