[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  
  # Frontend environment variables need to be prefixed with VITE_
  VITE_SUPABASE_URL = "https://itsxxdxyigsyqxkeonqr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0c3h4ZHh5aWdzeXF4a2VvbnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDQ1NjgsImV4cCI6MjA2NDg4MDU2OH0.YeWzwqm0FsIBs8ojIdyMSkprWn1OA4SfFgB2DM3j2ko"
  
  # Note: Server-side environment variables (SUPABASE_URL, SUPABASE_ANON_KEY, ADMIN_PASSWORD) 
  # should be set in Netlify dashboard under Site settings > Build & deploy > Environment variables
  # NEVER commit sensitive credentials to the repository!

# Enable Netlify Forms
[forms]
  processing = true

# Configure Netlify Dev
[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  autoLaunch = false

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
