[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Note: Sensitive environment variables like SUPABASE_URL, SUPABASE_ANON_KEY, 
  # EMAIL_USER, EMAIL_PASSWORD, and ADMIN_PASSWORD should be set in the Netlify 
  # dashboard under Site settings > Build & deploy > Environment variables
  
  # Frontend environment variables need to be prefixed with VITE_
  VITE_SUPABASE_URL = "${SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"

# Enable Netlify Forms
[forms]
  processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
