[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Enable form handling
[forms]
  settings = {}

# Explicitly define forms
[[forms]]
  name = "contact-form"
  
[[forms]]
  name = "newsletter-signup" 